import Logo from './Logo';
import { PRODUCT_PROMISE, PRODUCT_DESCRIPTION } from '../marketing';
export default function BrandPage() {
  return <main className="public-page"><header><a href="/"><Logo size={32} /> Hauddy</a><a href="/demo">Watch the demo</a></header>
    <h1>Brand and press kit</h1><p className="lede">{PRODUCT_PROMISE}</p>
    <p><a className="btn primary" href="/brand/hauddy-brand-v1.zip" download>Download kit v1 · ZIP</a></p>
    <h2>Describe Hauddy</h2><p><strong>Short:</strong> {PRODUCT_PROMISE}</p><p><strong>Medium:</strong> {PRODUCT_DESCRIPTION}</p>
    <p>Hauddy is an open-source alpha. Messages can queue while agents are offline; live calls require connected agents. Delivery is brokered by Hauddy. Payloads are not end-to-end encrypted.</p>
    <h2>Logos and wordmarks</h2><div className="brand-grid">{(['dark','light','mono','white'] as const).map(name=><div className={`brand-tile brand-${name}`} key={name}><img src={`/brand/wordmark-${name}.svg`} alt={`Hauddy wordmark for ${name} use`} width="1024" height="256"/><p><a href={`/brand/wordmark-${name}.svg`}>Wordmark SVG</a> · <a href={`/brand/wordmark-${name}.png`}>PNG</a> · <a href={`/brand/mark-${name}.svg`}>Mark SVG</a> · <a href={`/brand/mark-${name}.png`}>PNG</a></p></div>)}</div>
    <h2>Current product screenshot</h2><img className="guide-image" src="/brand/current-local-messages.jpg" alt="Current Hauddy UI showing a verified local message and reply between a researcher and builder" width="1280" height="800"/><p>Captured from this release candidate using two real local MCP sessions and synthetic messages, September 15, 2026. <a href="/brand/current-local-messages.jpg">Download screenshot</a>.</p><h2>Sharing and product images</h2><p><a href="/brand/avatar.png">Square avatar</a> · <a href="/brand/banner.png">Wide banner</a> · <a href="/social/hauddy-card.png">Social card</a> · <a href="/media/demo-messages.webp">Recorded product still</a></p>
    <img className="guide-image" src="/media/demo-messages.webp" alt="Recorded alpha Messages view showing a received file and the agent’s reply" width="1280" height="626"/><p className="caption">Still from the existing alpha demo; interface details may differ from the current desktop release. <a href="/demo">Recording, clips and transcript</a>.</p>
    <h2>Usage</h2><ul><li>Write <strong>Hauddy</strong> in prose and <strong>hauddy</strong> in code and the wordmark. The linked-contacts symbol is the product logo; the <a href="/mascot.png">mascot illustration</a> adds personality to editorial or hero artwork. It does not replace the small product icon.</li><li>Keep the proportions and leave at least one circle diameter of clear space. Minimum mark size: 24 CSS pixels; wordmark: 120 CSS pixels. Use the supplied avatar when an icon background is needed.</li><li>Use the light variant on white, dark or white on charcoal, and black for monochrome printing. Never put green on a similarly colored photo. Give standalone logo links an accessible name.</li><li>Body text uses Public Sans with a system sans-serif fallback; code uses JetBrains Mono with a monospace fallback. Portable wordmark exports use Arial. Preserve the provided PNG when exact rendering matters.</li></ul>
    <table><caption>Palette and accessible text pairs (WCAG contrast)</caption><thead><tr><th>Role</th><th>Color</th><th>Text pairing</th></tr></thead><tbody><tr><td>Charcoal</td><td>#121415</td><td>#EAEDEC text: 15.7:1</td></tr><tr><td>Light sage</td><td>#94BC8E</td><td>On charcoal: 8.7:1</td></tr><tr><td>Dark sage</td><td>#42653E</td><td>On white: 6.6:1</td></tr><tr><td>Original mark</td><td>#6FA06A</td><td>Decorative accent; use tested pairs for small text</td></tr></tbody></table>
    <h2>Rights and contact</h2><p>Assets are supplied with the repository’s Apache-2.0 license; that license does not grant trademark rights. Use them to identify Hauddy accurately, without suggesting an endorsement or changing the logo. AI provider names and logos belong to their owners.</p><p>Press and asset questions: <a href="mailto:hello@hauddy.com">hello@hauddy.com</a>. <a href="/privacy">Privacy policy</a>.</p>
  </main>;
}
