#!/usr/bin/env node
// Reads version from package.json and writes src/version.ts so the compiled
// sidecar carries its semver string without needing a runtime file read.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const { version } = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
writeFileSync(
  resolve(root, "src/version.ts"),
  `// Auto-generated by scripts/gen-version.mjs — do not edit by hand.\nexport const SIDECAR_VERSION = "${version}";\n`,
);
console.log(`gen-version: SIDECAR_VERSION = "${version}"`);
